import {CELL_TYPES} from "./cells/cell-types.js";

export class PlayingField {
    constructor() {
    }

    getFirstLevelStructure() {
        return [
            [CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.PLAYER_ON_EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.BOX_ON_EMPTY, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.EMPTY, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.TARGET, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL],
        ]
    };

    getSecondLevelStructure() {
        return [
            [CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.PLAYER_ON_EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.BOX_ON_EMPTY, CELL_TYPES.TARGET, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.BOX_ON_EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.TARGET, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.EMPTY, CELL_TYPES.WALL],
            [CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL, CELL_TYPES.WALL],
        ]
    }

    getAllLevels() {
        return [
            this.getFirstLevelStructure(),
            this.getSecondLevelStructure()
        ]
    }
}
