export const CELL_TYPES = {
    OUT_SPACE: 1,
    EMPTY: 2,
    WALL: 4,
    TARGET: 8,
    BOX: 16,
    PLAYER: 32
};
CELL_TYPES.BOX_ON_EMPTY =  CELL_TYPES.BOX | CELL_TYPES.EMPTY;
CELL_TYPES.BOX_ON_TARGET =  CELL_TYPES.BOX | CELL_TYPES.TARGET;
CELL_TYPES.PLAYER_ON_EMPTY =  CELL_TYPES.PLAYER | CELL_TYPES.EMPTY;
CELL_TYPES.PLAYER_ON_TARGET =  CELL_TYPES.PLAYER | CELL_TYPES.TARGET;
